rework; remove omarchy dependency

diff --git a/run_onchange_a0_pkg.sh.tmpl b/run_onchange_a0_pkg.sh.tmpl
--- a/run_onchange_a0_pkg.sh.tmpl
+++ b/run_onchange_a0_pkg.sh.tmpl
@@ -8,24 +8,24 @@ prompt() {
   echo -e "\n$RED>>>$NC $*"
 }
 
-pkg="arandr bat btop cmake curl fzf git npm nvim python3 sshfs tmux udiskie yazi zsh"
+pkg="arandr bat brave btop cmake curl dunst fzf git localsend network-manager-applet nextcloud npm nvim python3 sshfs tmux udiskie yazi zsh"
 
-arch_pkg=""
-deb_pkg="1337 0815"
+arch_pkg="yay hyprland hyprpaper xdg-desktop-portal-hyprland hyprlock hypridle nwg-displays walker elephant elephant-providerlist elephant-desktopapplications wiremix bluetui impala"
+deb_pkg=""
 
 {{ if eq .chezmoi.osRelease.id "arch" -}}
 
 prompt "ARCH BTW"
 sudo pacman -Sy
-for app in $pkg $arch_pkg; do
-  (sudo pacman -S --noconfirm --needed $app >/dev/null && echo -e "${GREEN}DONE${NC} install $app") || echo -e "${RED}ERROR${NC} install $app"
+for app in $arch_pkg $pkg; do
+  (sudo pacman -S --noconfirm --needed $app >/dev/null && echo -e "${GREEN}DONE PACMAN${NC} install $app") || (yay -S --noconfirm --needed $app >/dev/null && echo -e "${GREEN}DONE YAY${NC} install $app") || aecho -e "${RED}ERROR${NC} install $app"
 done
 
 {{ else if eq .chezmoi.osRelease.id "debian" -}}
 
 prompt "DEBIAN"
 sudo apt update
-for app in $pkg $deb_pkg; do
+for app in $deb_pkg $pkg; do
   (sudo apt-get install -y $prog >/dev/null && echo -e "${GREEN}DONE${NC} install $prog") || echo -e "${RED}ERROR${NC} install $prog"
 done
 
