fix install script

diff --git a/run_onchange_before_pkg.sh.tmpl b/run_onchange_before_pkg.sh.tmpl
--- a/run_onchange_before_pkg.sh.tmpl
+++ b/run_onchange_before_pkg.sh.tmpl
@@ -24,7 +24,7 @@ for app in $arch_pkg $pkg; do
   (sudo pacman -S --noconfirm --needed $app >/dev/null && echo -e "${GREEN}INSTALL DONE PACMAN${NC} install $app") || (yay -S --noconfirm --needed $app >/dev/null && echo -e "${GREEN}INSTALL DONE YAY${NC} install $app") || echo -e "${RED}ERROR${NC} install $app"
 done
 for app in $rm_pkg; do
-  (sudo pacman -Rns --noconfirm --needed $app >/dev/null && echo -e "${GREEN}REMOVE DONE PACMAN${NC} remove $app") || (yay -Rns --noconfirm --needed $app >/dev/null && echo -e "${GREEN}REMOVE DONE YAY${NC} remove $app") || echo -e "${RED}ERROR${NC} $app not installed"
+  (sudo pacman -Rns --noconfirm $app >/dev/null && echo -e "${GREEN}REMOVE DONE PACMAN${NC} remove $app") || (yay -Rns --noconfirm $app >/dev/null && echo -e "${GREEN}REMOVE DONE YAY${NC} remove $app") || echo -e "${RED}ERROR${NC} $app not installed"
 done
 
 {{ end -}}
